apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: flask-deployment

  template:
    metadata:
      labels:
        app: flask-deployment

    spec:
      containers:
        - name: flask-container
          image: chetanyagarg/flask_server:10
          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
